# Generated by Django 2.1.3 on 2018-11-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Categories', verbose_name='Категория выше')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(verbose_name='Время начало')),
                ('end_time', models.TimeField(verbose_name='Время конца')),
                ('exact_day', models.DateField(verbose_name='День')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Время бронирования',
                'verbose_name_plural': 'Времена бронирований',
            },
        ),
        migrations.CreateModel(
            name='ServiceNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Обслуживающий',
                'verbose_name_plural': 'Обслуживающие',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Categories', verbose_name='Категория')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Organizations', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='TimeOffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(null=True, verbose_name='Время начало')),
                ('end_time', models.TimeField(null=True, verbose_name='Время конца')),
                ('exact_day', models.DateField(null=True, verbose_name='Точная дата')),
            ],
            options={
                'verbose_name': 'Время отдыха',
                'verbose_name_plural': 'Времена отдыхов',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Roles', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Роли пользователя',
                'verbose_name_plural': 'Роли пользователей',
            },
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('order_number', models.IntegerField(verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.AddField(
            model_name='timeoffs',
            name='week_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='system.WeekDays', verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='servicenodes',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.Services', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='servicenodes',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.ServiceTypes', verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='servicenodes',
            name='servicer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Обслуживающий'),
        ),
        migrations.AddField(
            model_name='servicenodes',
            name='time_off',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.TimeOffs', verbose_name='Время отдыха'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='service_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.ServiceNodes', verbose_name='Обслуживающий'),
        ),
    ]
